Updated the PIN

diff --git a/src/pins/cex/clevis-decrypt-cex b/src/pins/cex/clevis-decrypt-cex
--- a/src/pins/cex/clevis-decrypt-cex
+++ b/src/pins/cex/clevis-decrypt-cex
@@ -1,16 +1,8 @@
-
-#%# Creating an decrypting pin
-#%#
-#%# Read README.md and clevis-encrypt-cex first, this file aims to
-#%# to avoid information duplication.
-#%# Unfortunately, this one uses a bashism (read -d) that is not at
-#%# all easy to eliminate.
-#!/bin/bash
-
-set -eu
-
-# Copyright (c) @year@ @name@
-# Author: @name@ <@email@>
+#!/bin/bash -e
+# vim: set tabstop=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
+#
+# Copyright (c) 2023 Madhu Pillai.
+# Author: madhupillai80@gmail.com <madhu.pillai1@ibm.com>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -23,11 +15,18 @@ set -eu
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
-#%# This program takes no options - everything needed to know will be
-#%# read from stdin.
+
+function on_exit() {
+    if [ ! -d "$TMP" ] || ! rm -rf "$TMP"; then
+        echo "Delete temporary files failed!" >&2
+        echo "You need to clean up: $TMP" >&2
+        exit 1
+    fi
+}
+
 [ $# -eq 1 ] && [ "${1:-}" = "--summary" ] && exit 2
 
 if [ -t 0 ] ; then
@@ -37,24 +36,46 @@ if [ -t 0 ] ; then
     exit 1
 fi
 
-#%# The input is concatenated using the dot. Read the first element
-#%# but leave everything else in the buffer. Only read -d can to that.
-read -d . hdr64
-#%# The header is base64-encoded. Decode now and also verify this is valid JSON
-if ! hdr="$(jose fmt --quote="$hdr64" --string --b64load --object --output=-)" ; then
-    echo 'JWE header corrupt' >&2
+#Verify the paes-s390 kernel module
+if ! lsmod | grep -q paes; then
+    modprobe paes 
+fi
+
+#Show Information about zcrypt devices and configuration.
+if ! command -v lszcrypt > /dev/null ; then
+    printf "s390x-tools not found"
+    exit 1
+fi
+
+#Verify the CEX card    
+if ! command lszcrypt -V > /dev/null; then
+    printf "Cex Card not found"
+    exit 1
+fi
+
+#Verify the CEX CARD present and atleast has a domain.
+card_domain=$(lszcrypt --ccaonly | awk '$1 ~ /^[0-9A-Fa-f]{2}\.[0-9A-Fa-f]{4}$/ {print $1}')
+if [ -z $card_domain ]; then
+    printf "No Crypto domain present"
+    exit 1
+    fi
+
+read -r -d . hdr64
+
+if ! hdr="$(jose b64 dec -i- <<< $hdr64 )"; then
+    echo "Error decoding JWE protected header!" >&2
     exit 1
 fi
 
 #%# Input validation: The pin must exist by name.
-if [ "$(jose fmt --json="$hdr" --get clevis --get pin --unquote=-)" != 'cex' ] ; then
-    echo 'JWE pin mismatch!' >&2
+if [ "$(jose fmt -j- -Og clevis -g pin -u- <<< "$hdr")" != "cex" ]; then
+    echo "JWE pin mismatch!" >&2
     exit 1
 fi
 
 #%# Load the parameters into shell variables.
-if ! keyfile="$(jose fmt --json="$hdr" --get clevis --get cex --get keyfile --unquote=-)" ; then
-    echo 'JWE missing 'clevis.cex.@param1@' header parameter!' >&2
+if ! keyfile="$(jose fmt --json="$hdr" --get clevis --get cex --get key --unquote=-)" ; then
+    echo 'JWE missing 'clevis.cex.key' header parameter!' >&2
     exit 1
 fi
 
@@ -62,6 +83,28 @@ if [ ! -f "$keyfile" ] ; then
     echo "Key file $keyfile not found" >&2
     exit 1
 fi
+
+
+mkdir -p "${TMPDIR:-/tmp}"
+if ! TMP="$(mktemp -d)"; then
+    echo "Creating a temporary dir for TPM files failed!" >&2
+    exit 1
+fi
+
+#Change the default zkey repository to tmp directory
+export ZKEY_REPOSITORY="/tmp/zkey"
+
+if ! jose b64 dec -i- -O "$TMP"/secure.skey <<< "$keyfile"; then
+    echo "Decoding secure key from Base64 failed!" >&2
+    exit 1
+fi
+
+if ! zkey val "$TMP"/secure.skey; then
+    echo "Secure Key validation failed!" >&2
+    exit 1
+fi
+
+jwk="$(jose b64 dec -i- <<< "$keyfile")"
 #if ! @param2@="$(jose fmt --json="$hdr" --get clevis --get cex --get @param2@ --unquote=-)" ; then
 #    echo 'JWE missing 'clevis.cex.@param2@' header parameter!' >&2
 #    exit 1
diff --git a/src/pins/cex/clevis-encrypt-cex b/src/pins/cex/clevis-encrypt-cex
--- a/src/pins/cex/clevis-encrypt-cex
+++ b/src/pins/cex/clevis-encrypt-cex
@@ -1,20 +1,9 @@
-#%# Creating an encrypting pin
-#%#
-#%# Read README.md first.
-#%#
-#%# The shell interpreter. For portability, it should have as little
-#%# requirements as possibly. Especially the decrypt should be executable
-#%# in busybox' ash as well
 #!/bin/sh
-
-#%# Some hardening. Safeguard against coding errors.
-set -eu
-
 #%# Legal stuff. Put your name etc. here.
 #%# Of course you're not bound to GPL-3+ but it will certainly ease
 #%# inclusion in upstream clevis if you use that.
-# Copyright (c) 2023 @name@
-# Author: madhupillai80@gmail.com
+# Copyright (c) 2023 Madhu Pillai
+# Author: Madhu Pillai <madhu.pillai1@ibm.com> 
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -31,10 +20,17 @@ set -eu
 #
 
 #%# A one-line summary. Will be used in the help messages below.
-SUMMARY='Encrypts using a IBM crypto express card (cex)'
+SUMMARY='Encrypts using a IBM CCA crypto express card (cex)'
 
-#%# Some option parsing, very simple.
-#%# Don't touch, it's hardcoded in the `clevis` program.
+function on_exit() {
+    if [ ! -d "$TMP" ] || ! rm -rf "$TMP"; then
+        echo "Delete temporary files failed!" >&2
+        echo "You need to clean up: $TMP" >&2
+        exit 1
+    fi
+}
+
+
 if [ "${1:-}" = '--summary' ] ; then
     echo "$SUMMARY"
     exit 0
@@ -43,33 +39,49 @@ fi
 #%# Regular operation assumes output goes to a file. If not, print
 #%# some usage information and bail out.
 if [ -t 0 ] ; then
-#!# Since this script runs in a pipe, *all* operational messages
-#!# must go to stderr.
     exec >&2
     echo
-#%# Don't be confused: This script is called from `clevis`, so
-#%# the usage text has spaces, not dashes.
-#%# Also, the configuration is in $1, see below.
-    echo 'Usage: clevis encrypt cex CONFIG < PLAINTEXT > JWE'
+    echo "Usage: clevis encrypt cex CONFIG < PLAINTEXT > JWE"
     echo
     echo "$SUMMARY"
     echo
-    echo 'This command uses the following configuration properties:'
+    echo "This command uses the following configuration properties:"
     echo
-#%# For the sake of users: Give a good explanation of your pin's
-#%# parameters.
-#%# Mandatory parameters should contain the string "REQUIRED"
-    echo '  keyfile: Secure key generated from CEX card (REQUIRED)'
+    echo "  keybits: <string>   Specifies the size of the AES key to be generated in bits.  Valid values are 128, 192, and 256 (default: 256)"
+    echo 
+    echo "  key-type: <string>   Specifies  the  key  type of the secure key. Possible values are CCA-AESDATA, CCA-AESCIPHER (default: CCA-AESDATA)"
     echo
-#%#    echo '  @mand2@: <string>  Another parameter @@ (REQUIRED)'
-#%#    echo
-#%# Optional parameters should mention the default value.
-#%#    echo '  @opt1@: <string>   An optional parameter @@ (default: @@)'
-#%#    echo
-#%# Pure visual: Make sure the short descriptions are aligned to the
-#%# same column.
+    echo "  volume-type: <string>    Specifies  the  volume  type of the associated volumes used with dm-crypt. Possible values are plain and luks2 (default: luks2)"
+    echo 
+    echo "  sector-size: <string>    Specifies the sector size in bytes used with dm-crypt. It must be a power of two and in the range of 512 to 4096 bytes (default: 512)"
+    echo
+    echo "  cipher-mode: <string>   Generates a secure AES key for the XTS cipher mode that consist of two concatenated secure keys (default: xts)"
+    echo
     exit 2
+
 fi
+
+#Verify the paes-s390 kernel module
+if ! lsmod | grep -q paes; then
+    modprobe paes 
+    fi
+#Show Information about zcrypt devices and configuration.
+if ! command -v lszcrypt > /dev/null ; then
+    printf "s390x-tools not found"
+    exit 1
+    fi
+#Verify the CEX card    
+if ! command lszcrypt -V > /dev/null; then
+    printf "Cex Card not found"
+    exit 1
+    fi
+
+#Verify the CEX CARD present and atleast has a domain.
+card_domain=$(lszcrypt --ccaonly | awk '$1 ~ /^[0-9A-Fa-f]{2}\.[0-9A-Fa-f]{4}$/ {print $1}')
+if [ -z $card_domain ]; then
+    printf "No Crypto domain present"
+    exit 1
+    fi
 
 #%# The CONFIG parameter in $1 has to be valid JSON
 if ! cfg="$(jose fmt --json="${1}" --object --output=- 2>/dev/null)" ; then
@@ -77,71 +89,120 @@ if ! cfg="$(jose fmt --json="${1}" --object --output=- 2>/dev/null)" ; then
     exit 1
 fi
 
-#%# Load the values from the configuration into shell variables.
-#%# Re-using the name is certainly a good idea
-#%#
-#%# For mandatory parameters it's like that:
-if ! key="$(jose fmt --json="$cfg" --object --get keyfile --unquote=-)" ; then
+keybits="$(jose fmt -j- -Og keybits -u- <<< "$cfg")" || keybits="256"
+
+key-type="$(jose fmt -j- -Og key-type -u- <<< "$cfg")" || key-type="CCA-AESDATA"
+
+volume-type="$(jose fmt -j- -Og volume-type -u- <<< "$cfg")" || volume-type="luks2"
+
+sector-size="$(jose fmt -j- -Og sector-size -u- <<< "$cfg")" || sector-size="512"
+
+cipher-mode="$(jose fmt -j- -Og cipher-mode -u- <<< "$cfg")" || cipher-mode="xts"
+
+
+mkdir -p "${TMPDIR:-/tmp/zkey}"
+if ! TMP="$(mktemp -d)"; then
+    echo "Creating a temporary dir for TPM files failed!" >&2
+    exit 1
+fi
+
+trap 'on_exit' EXIT
+
+#Change the default zkey repository to tmp directory
+export ZKEY_REPOSITORY="/tmp/zkey"
+
+#Generate the secure key.
+zkey generate --name secure_key --keybits "${keybits}" --key-type "${key-type}" --"${cipher-mode}" --volume-type "${volume-type}" --sector-size "${sector-size}" --apqns "${card_domain}"  >&2 || fail=$?
+
+if [ -n $fail ]; then
+    echo "Creating Secure Key failed!" >&2
+    exit 1
+    fi
+
+if ! skey="$(jose b64 enc -I $TMPDIR/secure_key.skey)" ; then
     echo 'Missing the required keyfile property!' >&2
     exit 1
 fi
-#if ! @mand2@="$(jose fmt --json="$cfg" --object --get @mand2@ --unquote=-)" ; then
-#    echo 'Missing the required @mand2@ property!' >&2
-#    exit 1
-#fi
 
-#%# For optional parameters, use:
-#@opt1@="$(jose fmt --json="$cfg" --object --get @opt1@ --unquote=-)" || @opt1@='@@'
-
-#%# Possibly validate parameters. If a check can be done at *en*crypt
-#%# time, it should be done now.
-
-#%# Now everything is set up for your pin's business logic.
-#%#
-#%# Your jobs, in no particular order:
-#%#
-#%# 1. Have the key in `jwk`:
-#%# If you want to create a new key:
-#jwk="$(jose jwk gen --input='{"alg":"A256GCM"}')"
-#%# Feel free to use different algorithms for `"alg"`,
-#%# jose-jwk-gen(1) and jose-alg(1) have more on all this.
-#%#
-#%# Or, if you want to use an existing key, just load it into `jwk`
-#%# from wherever you got it from:
-if ! jwk="$(jose b64 enc -I "$key")"; then
-    echo "Encoding jwk in Base64 failed!" >&2
+if ! jwk="$(jose jwk gen -i '{"alg":"A256GCM"}')"; then
+    echo "Generating a jwk failed!" >&2
     exit 1
 fi
-#%# Remember the result must be a valid jwk object.
 
-#%# 2. Store the key somewhere. That's your logic.
-#store_the_jwk "$jwk"
-#%# It is a good idea to store the entire `$jwk`. If you want to
-#%# extract the actual key, use
-#%#     jose fmt --json="$jwk" --object --get k --unquote=-
-#%# ... but you're probably wrong if you want to do that.
-
-#%# 3. Assemble all the information you will need to re-create
-#%# the key later in `jwe`:
-#%#
-#%# First create a skeleton that declares the pin, and creates a store.
 jwe='{"protected":{"clevis":{"pin":"cex","cex":{}}}}'
-#%# Then populate that store. Possibly you'll just have to pass
-#%# the parameters. Leave out those you will not need for decryption.
-#%# NB: The long form of the `-U` parameter of `jose fmt` is "--unwind"
-jwe="$(jose fmt --json="$jwe" --get protected --get clevis --get cex --quote "$jwk@" --set keyfile -UUUU --output=-)"
-#jwe="$(jose fmt --json="$jwe" --get protected --get clevis --get cex --quote "$@opt1@" --set @opt1@ -UUUU --output=-)"
+jwe="$(jose fmt -j "$jwe" -g protected -g clevis -g cex -q "$skey" -s key -UUUUo-)"
 
-#%# Almost there!
-#%# Forward everything to `jose jwe enc` which does the encryption job -
-#%# including reading the plaintext from stdin which gets replicated
-#%# using `cat`.
+# The on_exit() trap will not be fired after exec, so let's clean up the temp
+# directory at this point.
+[ -d "${TMP}" ] && rm -rf "${TMP}"
 
+exec jose jwe enc -i- -k- -I- -c < <(echo -n "$jwe$jwk"; /bin/cat)
 
-( printf '%s' "$jwe$jwk" ; cat ) | exec jose jwe enc --input=- --key=- --detached=- --compact
-
-#jose jwe enc -i- -k- -I- -c <<< "$(echo -n "$jwe$jwk"; /bin/cat)"
-#%# Anything that follows is executed only if jose failed.
-#%#
-#!# When using mktemp or the like, cleaning up has to be done
-#!# manually. See clevis-{en,de}crypt-tpm2 for an example.
+##%# Load the values from the configuration into shell variables.
+##%# Re-using the name is certainly a good idea
+##%#
+##%# For mandatory parameters it's like that:
+#if ! key="$(jose fmt --json="$cfg" --object --get keyfile --unquote=-)" ; then
+#    echo 'Missing the required keyfile property!' >&2
+#    exit 1
+#fi
+##if ! @mand2@="$(jose fmt --json="$cfg" --object --get @mand2@ --unquote=-)" ; then
+##    echo 'Missing the required @mand2@ property!' >&2
+##    exit 1
+##fi
+#
+##%# For optional parameters, use:
+##@opt1@="$(jose fmt --json="$cfg" --object --get @opt1@ --unquote=-)" || @opt1@='@@'
+#
+##%# Possibly validate parameters. If a check can be done at *en*crypt
+##%# time, it should be done now.
+#
+##%# Now everything is set up for your pin's business logic.
+##%#
+##%# Your jobs, in no particular order:
+##%#
+##%# 1. Have the key in `jwk`:
+##%# If you want to create a new key:
+##jwk="$(jose jwk gen --input='{"alg":"A256GCM"}')"
+##%# Feel free to use different algorithms for `"alg"`,
+##%# jose-jwk-gen(1) and jose-alg(1) have more on all this.
+##%#
+##%# Or, if you want to use an existing key, just load it into `jwk`
+##%# from wherever you got it from:
+#if ! jwk="$(jose b64 enc -I "$key")"; then
+#    echo "Encoding jwk in Base64 failed!" >&2
+#    exit 1
+#fi
+##%# Remember the result must be a valid jwk object.
+#
+##%# 2. Store the key somewhere. That's your logic.
+##store_the_jwk "$jwk"
+##%# It is a good idea to store the entire `$jwk`. If you want to
+##%# extract the actual key, use
+##%#     jose fmt --json="$jwk" --object --get k --unquote=-
+##%# ... but you're probably wrong if you want to do that.
+#
+##%# 3. Assemble all the information you will need to re-create
+##%# the key later in `jwe`:
+##%#
+##%# First create a skeleton that declares the pin, and creates a store.
+#jwe='{"protected":{"clevis":{"pin":"cex","cex":{}}}}'
+##%# Then populate that store. Possibly you'll just have to pass
+##%# the parameters. Leave out those you will not need for decryption.
+##%# NB: The long form of the `-U` parameter of `jose fmt` is "--unwind"
+#jwe="$(jose fmt --json="$jwe" --get protected --get clevis --get cex --quote "$jwk@" --set keyfile -UUUU --output=-)"
+##jwe="$(jose fmt --json="$jwe" --get protected --get clevis --get cex --quote "$@opt1@" --set @opt1@ -UUUU --output=-)"
+#
+##%# Almost there!
+##%# Forward everything to `jose jwe enc` which does the encryption job -
+##%# including reading the plaintext from stdin which gets replicated
+##%# using `cat`.
+#
+#
+#( printf '%s' "$jwe$jwk" ; cat ) | exec jose jwe enc --input=- --key=- --detached=- --compact
+#
+##jose jwe enc -i- -k- -I- -c <<< "$(echo -n "$jwe$jwk"; /bin/cat)"
+##%# Anything that follows is executed only if jose failed.
+##%#
+##!# When using mktemp or the like, cleaning up has to be done
+##!# manually. See clevis-{en,de}crypt-tpm2 for an example.
